class AuthenticationException(RuntimeError):
    pass


class UserAlreadyExistException(RuntimeError):
    pass
